version: 3

vars:
  APP_NAME: StrongDMM
  BIN_EXT:
    sh: echo '{{if eq OS "windows"}}.exe{{end}}'
  BIN_NAME:
    sh: echo '{{.APP_NAME}}{{.BIN_EXT}}'

tasks:
  run:
    deps:
      - build-sdmmparser
    dir: src
    cmds:
      - go run .

  build:
    deps:
      - build-sdmmparser
    dir: src
    cmds:
      - go build -trimpath -ldflags="-s -w" -o "../dst/{{.BIN_NAME}}" .

  build-sdmmparser:
    dir: src/third_party/sdmmparser/src
    cmds:
      - cargo build --release
