version: 3

vars:
  APP_NAME: StrongDMM
  BIN_EXT:
    sh: echo '{{if eq OS "windows"}}.exe{{end}}'
  BIN_NAME:
    sh: echo '{{.APP_NAME}}{{.BIN_EXT}}'
  EXTLD_FLAGS:
    sh: echo '{{if eq OS "windows"}}-static{{end}}'
  LD_FLAGS: -extldflags={{.EXTLD_FLAGS}} -s -w
  BUILD_FLAGS: -trimpath -ldflags="{{.LD_FLAGS}}" -o "../dst/{{.BIN_NAME}}"

tasks:
  run:
    deps:
      - build-sdmmparser
    dir: src
    cmds:
      - go run .

  build:
    deps:
      - build-sdmmparser
    dir: src
    cmds:
      - go build {{.BUILD_FLAGS}} .

  build-sdmmparser:
    dir: src/third_party/sdmmparser/src
    cmds:
      - cargo build --release
