version: 3

includes:
  task_win:
    taskfile: ./Taskfile_windows.yml
    optional: true

vars:
  GIT_VERSION:
    sh: git describe --tags --always
  GIT_REV:
    sh: git rev-parse --short HEAD
  APP_NAME: StrongDMM
  BIN_DST: ../dst/{{.APP_NAME}}{{exeExt}}
  BUILD_VARS: -X sdmm/env.Version={{.GIT_VERSION}} -X sdmm/env.Revision={{.GIT_REV}}
  LD_FLAGS_WINDOWS:
    sh: echo '{{if eq OS "windows"}}-H windowsgui -extldflags=-static{{end}}'
  LD_FLAGS: -s -w {{.BUILD_VARS}} {{.LD_FLAGS_WINDOWS}}
  BUILD_ARGS: -trimpath -ldflags="{{.LD_FLAGS}}"

tasks:
  run:
    deps:
      - build-sdmmparser
    dir: src
    cmds:
      - go run {{.BUILD_ARGS}} .

  build:
    deps:
      - build-sdmmparser
    dir: src
    cmds:
      - go build {{.BUILD_ARGS}} -o "{{.BIN_DST}}" .

  build-sdmmparser:
    dir: src/third_party/sdmmparser/src
    cmds:
      - cargo build --release
