[package]
name = "sdmmparser"
version = "0.0.1"

[[bin]]
name = "sdmmparser"
path = "main.rs"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[dependencies.dreammaker]
git = "https://github.com/SpaiR/SpacemanDMM"
rev = "e6c132d12bd304e38d5fb657e27619f4aca3ebd4"
package = "dreammaker"

[profile.release]
lto = true
