[package]
name = "sdmmparser"
version = "1.0.0"

[[bin]]
name = "sdmmparser"
path = "main.rs"

[dependencies]
serde = "1.0.106"
serde_derive = "1.0.106"
serde_json = "1.0.51"

[dependencies.dreammaker]
git = "https://github.com/SpaiR/SpacemanDMM"
rev = "c4e5161647c1a2c85b4bff42a1a3499f5b139b26"
package = "dreammaker"

[profile.release]
lto = true
