name: Feature Request
description: Suggest an idea for this project
title: "Feature Request: "
labels: [ enhancement ]
body:
  - type: textarea
    attributes:
      label: Problem to be solved
      description: Present a concise description of the problem to be addressed by this feature request.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Sugest a solution
      description: A concise description of your preferred solution.
  - type: markdown
    attributes:
      value: |
        Post additional information or images if you need so. If there are multiple solutions, please present each one separately. Save comparisons for the very end.
