name: CI
on: [ push ]
env:
  GO_VERSION: 1.17.8
jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    env:
      LINT_VERSION: v1.44.2
    steps:
      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.1.0
        with:
          version: ${{ env.LINT_VERSION }}
          working-directory: src

  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        include:
          - os: ubuntu-latest
            rust-target: stable-x86_64-unknown-linux-gnu
          - os: windows-latest
            rust-target: stable-x86_64-pc-windows-gnu
          - os: macos-latest
            rust-target: stable-x86_64-apple-darwin
    runs-on: ${{ matrix.os }}
    name: Build - ${{ matrix.os }}
    steps:
      - if: matrix.os == 'ubuntu-latest'
        name: Dependecies (Linux)
        run: |
          sudo apt clean
          sudo apt update
          sudo apt install xorg-dev libgtk-3-dev

      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Setup Rust
        run: |
          rustup install ${{ matrix.rust-target }}
          rustup default ${{ matrix.rust-target }}

      - name: Setup Task
        uses: arduino/setup-task@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Cache Build Files
        uses: actions/cache@v2
        with:
          path: |
            src/third_party/sdmmparser/src/target
          key: build-files-${{ matrix.os }}

      - if: matrix.os == 'windows-latest'
        name: Pre Build (Windows)
        run: task task_win:gen_syso

      - name: Build
        run: task build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ runner.os }}
          path: dst/*
          if-no-files-found: error

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v') # if tag starts with "v"
    steps:
      - name: Setup Task
        uses: arduino/setup-task@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download Release Files
        uses: actions/download-artifact@v2
        with:
          path: dst/

      - name: Prepare Release Files
        run: task release-files

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          prerelease: false
          files: |
            dst/bin/**
            dst/archive/**
